### ISSUE TITLE
Is their a way to get a Depth Map (aligned with original image)?

### ISSUE THREAD

**Issue by nosy-b** [sfu-gruvi-3dv/Self-Supervised-Human-Depth#2]
HI!
I wanted to generate a depth map aligned with original image using the output depth in npy. But it's not a depth map, more an approximated depth from a close 3D model (SIMPL)
Is it a limitation of the algorithm or should I access the depth before the last step?
Here is the superposition of the depth image (only 1 z) and original image we can see the problem.

Thank you!
![depthMapHuman](https://user-images.githubusercontent.com/158514/107126884-c1cf7c80-68b2-11eb-9009-3e97e86bf179.jpg)

**Comment by feitongt** [comment]
Hi,

The base depth is rendered from the SMPL model which is estimated from TrackNet. It seems TrackNet did not perform well on this sample and SMPL is not aligned well in the image. Here is a link (https://vault.sfu.ca/index.php/s/lcyAcQLC8i4Wy45) to the other pretrained TrackNet model. You can try to use this one. You can also try some other state-of-the-art SMPL estimation methods to replace the original TrackNet for better performance.
